### ISSUE TITLE
[niina] Let's extract all methods which does not access member variables

### ISSUE THREAD

**Issue by peria** [puyoai/puyoai#102]
`COMAI_HI` has so many class that it is difficult to read.  However, most of them do not access to member variables nor global variables.
Let's extract them to other file.  Then we can do refactoring for each files independently.

**Comment by mayah** [comment]
Maybe most of the methods are extracted? I'm not sure we have to extract tobashi_hantei.

**Comment by peria** [comment]
ah, right.  we can do it, but it is not required.
Let me close this issue.  Thank you for your works!
