### ISSUE TITLE
Is the binary folder implicitly specified under the project folder?

### ISSUE THREAD

**Issue by gecko655** [puyoai/puyoai#112]
The project seems to specify that the binary folder must be located under the project root folder,
but it is not explained in the Readme.md

My suggestion is:
 - To explain "binary folder must be located under the project root folder" on readme.md
 - To specify binary folder to be located programmatically (perhaps on cmakelists.txt)
 - To make the project able to run apart from the project folder.

Which is the best you think? Other solutions?

A problem happens when using IDEs that will (by default) output the binaries to IDE's own folder.
For example, Mac OS X version [CLion](https://www.jetbrains.com/clion/ "") outputs binaries under the folder "$HOME/Library/Caches/clion10/cmake/generated/3945187d/3945187d/".

The problem can be reproduced by command line.
Here is the example of the reproduction.
```
$ cd ~/Documents/tmp/testPuyoAiBuild/
$ cmake ~/git/puyoai/src/
(omit)
$ make -j8
(omit)
$ ./duel/duel ./cpu/sample/sample ./cpu/sample/sample

F0711 10:54:01.270409 1996407552 screen.cc:54] Font not found
*** Check failure stack trace: ***
@ 0x10fda9076 google::LogMessage::Fail()
@ 0x10fda8757 google::LogMessage::SendToLog()
@ 0x10fda8cc5 google::LogMessage::Flush()
@ 0x10fdac015 google::LogMessageFatal::~LogMessageFatal()
@ 0x10fda9363 google::LogMessageFatal::~LogMessageFatal()
@ 0x10fbe018a Screen::init()
@ 0x10fbe039b Screen::Screen()
@ 0x10fbdf651 MainWindow::MainWindow()
@ 0x10fbd91da main
@ 0x7fff86d8c5c9 start
@ 0x3 (unknown)
Abort trap: 6
```
screen.cc:54:
```cpp
    char buf[PATH_MAX+1];
    if (!getcwd(buf, PATH_MAX))
        PLOG(FATAL) << "buffer is too small for getcwd";

    char* p = buf;
    while (true) {
        string font_filename = string(p) + "/data/mikachan-p.ttf";
        if (access(font_filename.c_str(), R_OK) == 0) {
            font_ = TTF_OpenFont(font_filename.c_str(), 16);
            if (!font_) {
                LOG(FATAL) << TTF_GetError();
            }
            break;
        }

        p = dirname(p);
        if (!p[1]) {
            LOG(FATAL) << "Font not found"; //line 54 is here.
        }
    }
```

The code assumes  "/data/mikachan-p.ttf" can be found above the binary folder.

Thank you for your consideration!

**Comment by peria** [comment]
A way to solve the trouble you got is make a symbolic link to [data/](https://github.com/puyoai/puyoai/tree/master/data) under your `$HOME`. 
   $ cd
   $ ln -s ~/git/puyoai/data

Anyway, we did not work for the portability to build anywhere.  So we should do something for it.
(And there must be more TODOs undescribed in README.)

- To explain "binary folder must be located under the project root folder" on readme.md
I don't think this idea is good.  First of all, displaying in GUI window is an optional feature, and README.md is just an introduction.  The issue around file paths does not happen if you use commands as README.md says.

- To specify binary folder to be located programmatically (perhaps on cmakelists.txt)
- To make the project able to run apart from the project folder.
So we should do to achieve one of these ideas, and I recommend the first one. (make it configurable)
We may use environment variables of CMake to output the root directory of repository to files under output directories.

**Comment by gecko655** [comment]
Thank you for your quick consideration. I also agree with @peria.

I worked on making cmake to run on each environment, but I couldn't make compatible cmake yet.
If I succeeded to make it someday, I'll create PR.

**Comment by peria** [comment]
Thank you for your contributions!  We're looking forward to your PRs.

**Comment by mayah** [comment]
Ah, actually this is a hard problem. We'd like to see data/ directory somehow, however, it is bothersome to specify before building. So currently we always assume that SRC_DIR etc. are always located on the same directory.

You might be able to define SRC_DIR etc. before building? Not sure, though...

puyoai_add_cxx_flags("-DSRC_DIR=\\\"${CMAKE_SOURCE_DIR}\\\"")
puyoai_add_cxx_flags("-DTESTDATA_DIR=\\\"${CMAKE_SOURCE_DIR}/../testdata\\\"")
puyoai_add_cxx_flags("-DDATA_DIR=\\\"${CMAKE_SOURCE_DIR}/../data\\\"")
puyoai_add_cxx_flags("-DRECOGNITION_DIR=\\\"${CMAKE_SOURCE_DIR}/../recognition\\\"")

**Comment by mayah** [comment]
Another option is to copy data/ directory to out/Release (the directory you did cmake).
Actually I have chosen this approach at first. However, after we update data/ resource, we have to re-run cmake, and I really often forgot doing so. So I changed to the current design, to see the src/ etc.

**Comment by mayah** [comment]
WONTFIX. Currently I don't have any plan to move this.
You can feel free to reopen if this is important (e.g. if it's necessary for windows build etc.)
