### ISSUE TITLE
[niina] Merge hon_syoukyo and hon_syoukyo_score

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#118]
These are almost the same.

Just set *score and *quick only when they're not nullptr?
Then we can remove hon_syoukyo().

**Comment by mayah** [comment]
Needs test before merging them.

**Comment by peria** [comment]
`hon_syoukyo()` is no longer used, and we can remove it.
Remained `hon_syoukyo_score()` also can be replaced with `simulate()`.
