### ISSUE TITLE
syou() deletes the next YELLOW puyo to the fired puyo, instead of OJAMA puyo.

### ISSUE THREAD

**Issue by gecko655** [puyoai/puyoai#124]
I understand that syou() function in `test_lockit/field.cc` is a function to delete "(x,y) puyo", its "connected puyos" and "involving OJAMA puyo".
https://github.com/puyoai/puyoai/blob/master/src/cpu/test_lockit/field.cc#L132

As far as I read the code, the code above seems to use magic number **6** for OJAMA puyo, but OJAMA is defined '1' here: https://github.com/puyoai/puyoai/blob/master/src/core/puyo_color.cc#L11

Maybe, is it critical for niina? :-<

**Comment by peria** [comment]
niina uses other definition of colors.
Please refer https://github.com/puyoai/puyoai/blob/master/src/cpu/test_lockit/color.h for the details.

We have replaced some magic numbers with TLColor, but there can be remained ones....

**Comment by mayah** [comment]
niina is using different colors to ours.

https://github.com/puyoai/puyoai/blob/master/src/cpu/test_lockit/color.h

However, what is 6?

**Comment by gecko655** [comment]
6 is here: https://github.com/puyoai/puyoai/blob/master/src/cpu/test_lockit/field.cc#L132

```c++
    if ((x != 0) && (ba[x - 1][y] == 6)) {
        ba[x - 1][y] = 0;
        flg[x - 1] = 1;
    }
```
```ba[x - 1][y] == 6``` seems to judge whether the left puyo is OJAMA,
and if so, the left puyo will be deleted.

**Comment by peria** [comment]
Hmmm, I grepped 6 in other code for niina, but found nothing informative.

And as @gecko655 says, the behavior seems to be like OJAMA.
I think we can replace 6 in field.cc with TLColor::OJAMA.

**Comment by mayah** [comment]
maybe they should be replaced with TLColor::OJAMA, I believe?

**Comment by peria** [comment]
I'm happy if you replace other magic numbers (like '0' for `TLColor::EMPTY`) together.

**Comment by gecko655** [comment]
So, I'll create a pull request soon!

**Comment by gecko655** [comment]
By the way,  the function, syou() is, for me, too confusing name.
At first I read it as "show" (typo) and I also think about 小 and 省.
Can it be shoukyo() or delete(), or other clear name?

**Comment by peria** [comment]
Right. The names of functions and variables for niina are almost described in Japanese.

Pros for it is that we can tell functions and variables with English names are created by our refactoring. :)

**Comment by peria** [comment]
As you may know, functions in `test_lockit/` has many many parts to be modified or cleaned up.
One of our goal is rewrite code of niina in our frameworks under `core`, so I don't recommend you to work  for just renaming which will be removed soon.

**Comment by mayah** [comment]
Yeah. niina's code looks too redundant for us, and we've tried re-writing it several times. However, it was too hard to understand the correct behavior for us. So now we're making it as simple as possible. Could be a long road though...

**Comment by gecko655** [comment]
I all understood. It looks so hard to refactor...
