### ISSUE TITLE
[niina] Replace magic numbers with named values

### ISSUE THREAD

**Issue by peria** [puyoai/puyoai#128]
It is difficult to get what a magic number means.
For example, we assumed ojama puyos in a field were figured by '9', but '6' seems correct. (It was wrong from the beginning.)

Current candidates are
- numbers in fields --> colored puyos, ojama puyos, empty cell, etc.
- numbers in `point[][]`.  It seems a boolean table in many cases, but in some cases, it has numbers.

**Comment by peria** [comment]
Are there any remained magic numbers?

**Comment by mayah** [comment]
Now that all color is PuyoColor.
To be strict, we should use kWidth instead of 6, etc.
However, I'm OK to close this since all color is changed to PuyoColor.

**Comment by peria** [comment]
Other AIs also uses 6 for WIDTH, and 12 for HEIGHT.
`point2[]` is still using magic numbers, but I think it better to just put a comment what each number means.
