### ISSUE TITLE
[niina] niina sometimes make decision (x,r) = (1,3)

### ISSUE THREAD

**Issue by gecko655** [puyoai/puyoai#131]
niina sometimes falls the tsumo naturally (makes no operation) in my emulator environment.
I investigated it and found that niina decided to fall the tsumo to (x,r) = (1,3), which is out of the field.

In my observation, this always happens when a new game starts and the first tsumo is ZORO (2 same color puyos).
(I can't affirm, but) I think this might result in #83.

I observed by adding logging code. (https://github.com/gecko655/puyoai/blob/13decision/src/cpu/test_lockit/cpu.cc#L258 )
Then I observe the log below.
```
$ ./duel/duel ./cpu/test_lockit/niina ./cpu/sampleample
E0713 00:20:46.029913 1996407552 cpu.cc:258] (1, 3)false
E0713 00:20:51.499569 1996407552 cpu.cc:258] (2, 0)true
E0713 00:20:52.714907 1996407552 cpu.cc:258] (1, 0)true
E0713 00:20:54.008599 1996407552 cpu.cc:258] (3, 3)true
E0713 00:20:55.372921 1996407552 cpu.cc:258] (4, 2)true
E0713 00:20:58.207978 1996407552 cpu.cc:258] (3, 0)true
E0713 00:20:59.107482 1996407552 cpu.cc:258] (6, 0)true
```

If it is just my environment probrem and no other one encounters this problem, please ignore this issue.

**Comment by peria** [comment]
It reproduces on my environment.  Thank you for the confirmation.
I think it comes from https://github.com/puyoai/puyoai/commit/882e9ea86721fcba422e6d6ba807ad4fbf4de5c8

I'll fix it soon.

**Comment by gecko655** [comment]
:+1: The update works for me. Thanks!
