### ISSUE TITLE
Make 5-rensa AI

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#171]
It tries to make 5-rensa as fast as possible.

**Comment by peria** [comment]
9f718756b42106545453055452b954dc28724cca can be a solution for this issue.
I will update the AI to evaluate frame times, and will move to sample/ directory.

I thank @takapt very much to have introduced a very useful algorithm.

**Comment by peria** [comment]
37adfb258ff81a65a25f4a273d766c7375b62258 is an AI to fire short 連鎖s as strong as 2-double.

I'd like to merge those 2 AIs' code, and move them to `sample/` directory.

**Comment by mayah** [comment]
I feel sample_beam/run_full.sh works well. maybe ok to close this.
