### ISSUE TITLE
Consider CoreField::hash()

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#186]
@takapt and @peria (full) define uint64 hashField(const CoreField&), but it would be better to define CoreField::hash() if many people use it.

My idea is: define BitField::hash() and CoreField::hash() should just use it.
BitField::hash() could be fast if we can utilize xmm register correctly.

Probably it would be good if it's compatible with std::hash. So returning size_t is better.

**Comment by peria** [comment]
+1

**Comment by mayah** [comment]
59b4d94a5053ad9665f4bbcc072f369b31c8836e
