### ISSUE TITLE
BitField::hash conflicts more than expected?

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#190]
According to @takapt 's comment, it conflicts a lot.
Needs to be verified and fixed.

probably just multiplying 33 is not good here.
larger value will fix this?

**Comment by mayah** [comment]
opps... and fixed.

probably just multiplying 33 is not good here.
larger value will fix this?

**Comment by mayah** [comment]
maybe we should have used a value that has more 1 bits

**Comment by takapt** [comment]
Using 10^9 instead of 33 makes less collisions.

**Comment by mayah** [comment]
how to verity?

**Comment by mayah** [comment]
s/verity/verify/

**Comment by takapt** [comment]
I insert code to print information in my ai code. its bad way.
We should write unit test.

**Comment by mayah** [comment]
then could you write down your result here?

**Comment by mayah** [comment]
collision rate or the number of collisions

**Comment by takapt** [comment]
I tried to generate random 1000000 fields and check collisions, but no collisions are found.

**Comment by mayah** [comment]
Then, probably, we should make fields that a kumipuyo (or multiple kumipuyo?) is put?

**Comment by takapt** [comment]
My AI has many collisions, so I checked collisions in my AI.
In my AI code, I replace unordered_set\<int64_t\> to unordered_set\<CoreField\> and insert below code after next_states calls
```
        unordered_map<size_t, int> collision_counter;
        for (auto& f : visited)
            ++collision_counter[f.hash()];
        int collisions = 0;
        for (auto& it : collision_counter)
            collisions += it.second - 1;
        double rate = (double)collisions / visited.size();
        if (rate > 0.05)
            printf("%.5f (%5d / %5lu)\n", rate, collisions, visited.size());

```

Output of Endless::run()
Use 33
(print if collisions rate > 0.5)
```
0.05077 (  109 /  2147)
0.05041 (   73 /  1448)
0.05204 (  171 /  3286)
0.07364 (  355 /  4821)
0.05519 (  116 /  2102)
0.05776 (   96 /  1662)
0.12995 (  312 /  2401)
0.05164 (  187 /  3621)
0.06957 (  150 /  2156)
0.05525 (  122 /  2208)
0.05436 (  154 /  2833)
0.06529 (  202 /  3094)
0.06624 (  321 /  4846)
0.07743 (  306 /  3952)
0.07284 (   96 /  1318)
0.05904 (  227 /  3845)
0.05838 (   23 /   394)
```

Use 10^9 + 9
(print if at least one collision)
```
0.00052 (    2 /  3821)
0.00035 (    1 /  2892)
0.00034 (    1 /  2944)
0.00206 (    6 /  2907)
0.00045 (    1 /  2236)
0.00051 (    2 /  3920)
```

**Comment by mayah** [comment]
Thanks!

**Comment by peria** [comment]
携帯からエスパーしてみる。
33は2^5+1というのが悪さして、前の情報が殆どスクランブルされない。恐らく
"RB    " と "R B   " は同じ値を返すんじゃないかなー。
なので、33にもう1ビット追加、というのも悪くない案だと思う。

**Comment by mayah** [comment]
任意の1個もしくは2個のぷよを含んだフィールドでかぶらないことは、ユニットテストで保証してはいます。

hashなんでという理由で適当に33選びましたが、不適当でした。
