### ISSUE TITLE
cpu/peria/quick_full does not compile on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#193]
gcc: gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4 

sorry, unimplemented: non-trivial designated initializers not supported
   };
   ^

.first_decision = Decision(0, 0)
is bad.

Anyway this is C99, and C++11 does not allow this, though most compilers support it.

**Comment by mayah** [comment]
Line 109 in quick_full.cc

**Comment by peria** [comment]
54e56ccbcfb8dce05918f5a3d32115df79331696 would be a fix for this issue, though I did not check it w/ gcc yet.

**Comment by mayah** [comment]
Checking on my env, it turns out you need to specify all the fields in the designated initializer.

**Comment by mayah** [comment]
Sorry. .first_decision is not bad at all :-(

**Comment by peria** [comment]
I got it.  Thank you for the fix.
