### ISSUE TITLE
make error on 32bit environment

### ISSUE THREAD

**Issue by hryshtk** [puyoai/puyoai#202]
32bit環境で動かすのは無理ですか？

**Comment by mayah** [comment]
申し訳ありませんが、現開発者のうち誰も32bit環境で開発、テストをしていません。

**Comment by mayah** [comment]
ハチ公視点で左前

**Comment by mayah** [comment]
なんかよく分からん誤爆をした

**Comment by mayah** [comment]
なお、僕は32bit環境をいまさら作る気はまったくないので、自分で動かしてもらってパッチ送ってもらうしか……。

**Comment by hryshtk** [comment]
ですよねー。。。

**Comment by mayah** [comment]
エラーとだけ書かれても我々はどうしようもないです。ちゃんとエラーの内容を書いていただければ、なんとかするかもしれません。

色々な環境でビルドできることはコードの質の高さを示しますから、質の低いコードによってエラーになっているのなら直すかもしれません。

少なくともhash()がコンパイルできないのは知っているので、それ以外でエラーになっている場所があれば書き込んでください。

**Comment by peria** [comment]
もし直していただける、もしくは直すことに協力していただけるなら、コンパイル環境とerror内容はせめて教えて下さい。
ただ常時サポートする予定はありません。
