### ISSUE TITLE
Are variable names wrong in vanishing methods of FieldBits?

### ISSUE THREAD

**Issue by takapt** [puyoai/puyoai#203]
例えば、FieldBits::findVanishingBitsで使われている変数u, dは付けるべき変数名が逆になっていませんか。
u.get(x, y) == this->get(x, y) && this->get(x, y - 1)と今はなっていますが、
u.get(x, y) == this->get(x, y) && this->get(x, y + 1)となるべきではないですか。

**Comment by mayah** [comment]
そう捉えるなら実はlとrも反対で、xmmレジスタ上で左に2バイトシフトシフトするとぷよは右に移動する(リトルエンディアン)

**Comment by takapt** [comment]
今の実装は以下のCHECKが通るようになっています。
```
    for (int y = 1; y <= 13; ++y)
    {
        for (int x = 1; x <= 6; ++x)
        {
            CHECK(u.get(x, y) == (get(x, y) && get(x, y - 1)));
            CHECK(d.get(x, y) == (get(x, y) && get(x, y + 1)));
            CHECK(l.get(x, y) == (get(x, y) && get(x - 1, y)));
            CHECK(r.get(x, y) == (get(x, y) && get(x + 1, y)));
        }
    }
```

これを見ると、u, d, l, rはそれぞれ以下のような意味で取れます。
uはぷよを1段上(up)にずらしたものとandを取ったという意味
dはぷよを1段下(down)にずらしたものとand取ったという意味
lは(x, y)に着目したとき、ぷよがある && 左(left)のぷよと連結しているという意味
rは(x, y)に着目したとき、ぷよがある && 右(right)のぷよと連結しているという意味

そうするとu, dとl, rで変数名の意味が食い違っていると思います。どういう意図で変数名を付けたのですか。

**Comment by mayah** [comment]
間違っているとしたら単に錯誤です。
