### ISSUE TITLE
[AVX2] FieldBits256Test.expand fails

### ISSUE THREAD

**Issue by peria** [puyoai/puyoai#220]
```
[ RUN      ] FieldBits256Test.expand
/github/puyoai/src/core/field_bits_256_test.cc:67: Failure
Value of: expanded.high()
  Actual: 00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00010000
00000000

Expected: highExpected
Which is: 00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00010000
00010000
01110000
00000000

[  FAILED  ] FieldBits256Test.expand (0 ms)
```

It seems that `_mm256_slli_si256`, `_mm256_srli_si256`, `_mm256_srli_epi16`, and `_mm256_slli_epi16` operate only lower 128 bit part. <del>([similar question in stackoverflow](http://stackoverflow.com/questions/25248766/emulating-shifts-on-32-bytes-with-avx))
http://web.mit.edu/guilledc/www/avx2byteshift.h can be a good reference to operate all 256 bits at once, but I'm not sure it runs faster than `FieldBits`.</del>

**Comment by mayah** [comment]
on Windows? It passes on Mac & Linux (Haswell platform)

_mm256_slli_si256 generates VPSLLDQ instruction (https://software.intel.com/en-us/node/523972)
So, it should operates on both lower part and higher part.

TEMP ← COUNT
IF (TEMP > 15) THEN TEMP (cid:193) 16; FI
DEST[127:0] ← SRC[127:0] << (TEMP * 8)
DEST[255:128] ← SRC[255:128] << (TEMP * 8)

**Comment by mayah** [comment]
Note: _mm256_slli_si256 etc. operates shift for xmm higher part & xmm lower part separately. However, it is actually convenient for our purpose, since higher part and lower part contains different puyo (bit) field.

**Comment by mayah** [comment]
Could you write which compiler and which platform is used?

**Comment by peria** [comment]
I developed and ran tests in a virtual machine.

Guest machine:
- VM: VirtualBox 5.0.12 r104815
- OS: Ubuntu 14.04
- Compiler: clang 3.6 (with -mavx2)

Host machine:
- CPU: skylake family
- OS: Windows 7
- (Compiler: cl.exe in Visual Studio 2015)

Hmm, this issue may happen only on this VM.  It passes on the host machine.
In the VM, the behavior looks

```
TEMP ← COUNT
IF (TEMP > 15) THEN TEMP (cid:193) 16; FI
DEST[127:0] ← SRC[127:0] << (TEMP * 8)
DEST[255:128] ← 0
```

I'll check VirtualBox's release notes and updates.

**Comment by peria** [comment]
[This issue](https://www.virtualbox.org/ticket/14262) in VirtualBox can be the reason of this test failure.
Let me close it as won't fix. (´・ω・｀)
