### ISSUE TITLE
cpu/test_lockit/*.cpp can be merged

### ISSUE THREAD

**Issue by peria** [puyoai/puyoai#26]
`cpu/test_lockit/*.cpp` のファイルはほとんど違いがいないのでコンパイル時パラメータで振り分けられるようにするとメンテナンス性が上がる。

```
$ diff nidub.cpp rendaS9.cpp
21c21
< bool is_2dub_cpu = true;
---
> bool is_2dub_cpu = false;

$ diff nidub.cpp rendaGS9.cpp
8c8
< int e_t = 1;
---
> int e_t = 0;
11c11
< int y_t = 3;
---
> int y_t = 2;
14,15c14,15
< int o_t = 0;
< int p_t = 4;
---
> int o_t = 1;
> int p_t = 2;
18,21c18,21
< int takasa_point = 240; // G,S
< int ruiseki_point = 0; // T,S
< int renketu_bairitu = 4; // S
< bool is_2dub_cpu = true;
---
> int takasa_point = 240;
> int ruiseki_point = 6;
> int renketu_bairitu = 1;
> bool is_2dub_cpu = false;
```

**Comment by mayah** [comment]
現在coma.cppになっているものがなぜかもともとcoma.hで、３タイプほとんど完全コピーだったのをとりあえずここまで分離しました（超巨大な共通部分がくくり出せた格好）。main 以外をライブラリにするという方針で現状他のCPUも書かれてあるので、diffをとって外出しできる部分をextern変数としてとりあえずmainと同じファイルに外出ししました。

以前某所でメンテされていたものは、勝手にこの変数に基づいてコードを取り除いていた部分があるので、また本人に動きがおかしいと言われたこともあるので、今回の公開ではオリジナルを尊重してあります。

**Comment by mayah** [comment]
（方針案）
仮にコンパイル時に定数を与える場合、nidub.cpp などをすべて main.cc にまとめ、定数としてタイプを与えるにとどめ残りは ifdef で分岐。

**Comment by peria** [comment]
あー。diffしか見てなかったです。＆＆以前某所でメンテされていた時の記憶でissue登録してました。
長期的にはリファクタリングが必要かもしれませんが、現状はこれでOKだと思います。
