### ISSUE TITLE
Consider git submodule for third_party.

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#28]
Instead of adding them in this repository, I'd like to use git submodule.

**Comment by peria** [comment]
"them" in the description means libraries which is required.
Now it figures `glog` and `gflags`.

**Comment by peria** [comment]
Now `gtest` is available at https://github.com/google/googletest . Let's use it.

**Comment by mayah** [comment]
glog and gflags will be addressed in #27.
Now only jsoncpp is left

**Comment by peria** [comment]
IIRC, jsoncpp has something bad to import as a sub module. Right?
@mayah, Do you remember what it is?

**Comment by mayah** [comment]
jsoncpp does not have a good CMakeLists.txt just for using it as a library.

It is good if we run amalgamate.py and move dist/ directory to <out dir>/gen/jonscpp in our CMakeLists.txt. Don't read jsoncpp CMakeLists.txt.

**Comment by mayah** [comment]
All third_party libraries are now under git submodule. closing.
