### ISSUE TITLE
Needs more MSG

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#3]
I would like to show more MSG in duel CUI.

**Comment by mayah** [comment]
Now that MSG is divided into multiple lines with comma in gui viewer. Does anyone want to do in cui?

**Comment by peria** [comment]
I want a CUI environment, but is there any change in CUI?
If CUI environment will have an issue only in showing messages, I mean, it will run and show correct fields, I will work for the message issue.

**Comment by peria** [comment]
Close as a duplicate of #34.
