### ISSUE TITLE
Add organization image for puyoai

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#43]

**Comment by peria** [comment]
GUIでの表示について、実際のぷよと一緒にAIが何を考えてるか(どう作ろうとしているか)を表示するためのちょっと違うぷよの絵(多分半透明)が必要ということ。

**Comment by mayah** [comment]
これは puyoai のプロジェクトのアイコンがデフォルトのままで寂しいので、なんか良い画像を登録したい、という意味のつもりでした。

**Comment by peria** [comment]
つらぽ……(´・ω・`)
