### ISSUE TITLE
Don't call malloc() between fork() and exec()

### ISSUE THREAD

**Issue by mayah** [puyoai/puyoai#68]
stringstream might call malloc, so it's not recommended to use between fork() and exec().
Might be ok, but might not be ok.
I believe it's better not to call such functions between fork() and exec().

3118d864812054201439339c86ad26fe8a6595a1 might cause a problem.

**Comment by pascaljp** [comment]
Submitted https://github.com/puyoai/puyoai/commit/eaed3f9aa6c98573574089db5070c42996e6eeb1
