### ISSUE TITLE
Mapping between `aa` and (`x`, `r`) is wrong

### ISSUE THREAD

**Issue by peria** [puyoai/puyoai#71]
In `cpu/test_lockit/cpu.cc`, mapping between `aa`(`tmp`) and (`x`,`r`) seems wrong
https://github.com/puyoai/puyoai/blob/master/src/cpu/test_lockit/cpu.cc#L216-231

In other area, its mapping is like following.
- 0 <= aa < 6 : (x, r) = (aa + 1, 0)
- 6 <= aa < 12 : (x, r) = (aa - 6, 2)
- 12 <= aa < 17 : (x, r) = (aa - 12 + 1, 3)
- 17 <= aa < 22 : (x, r) = (aa - 17, 1)

**Comment by mayah** [comment]
Still wrong? Maybe we can write a function to map aa to (x, r) now, I believe.

**Comment by peria** [comment]
I think 882e9ea86721fcba422e6d6ba807ad4fbf4de5c8 fixed this issue.
Let me close it.
