### ISSUE TITLE
[niina] Niina does not control the first Tsumo on AC

### ISSUE THREAD

**Issue by peria** [puyoai/puyoai#83]
On AC environment, niina sometimes does not control the first tsumo.
`ID=12  YP=004445 OP=004445 YE=W------ OE=W------`

**Comment by peria** [comment]
Patches ed75806e4d508caa1be8c0a33b21a13b979a3fc8 and dd009f1d18caf1774676d238583b4ad078d09fbe made by mayah took a workaround.

Keep open this issue to go a right way.

**Comment by mayah** [comment]
closing
